import { z } from 'zod';
import { IJobResponse, ITaskResponse, OperationStatus } from '@map-colonies/mc-priority-queue';
import type { FeatureCollection, Polygon } from 'geojson';
import { ProcessingState } from '@map-colonies/shapefile-reader';
import {
  IngestionValidationTaskParams,
  PartFeatureProperties,
  polygonPartsPayloadSchema,
  ValidationAggregatedErrors,
} from '@map-colonies/raster-shared';
import { ingestionJobParamsSchema } from '../schemas/ingestion.schema';

type PolygonPartExtended = PartFeatureProperties &
  Omit<z.infer<typeof polygonPartsPayloadSchema>, 'partsDataChunk'> & {
    requestFeatureId: string;
    partId: string;
    ingestionDateUTC: Date;
    id: string;
  };

export interface IJobManagerConfig {
  jobManagerBaseUrl: string;
  heartbeat: IHeartbeatConfig;
  dequeueIntervalMs: number;
}

export interface IHeartbeatConfig {
  baseUrl: string;
  intervalMs: number;
}

export interface IJobAndTaskResponse {
  task: ITaskResponse<unknown>;
  job: IJobResponse<unknown, unknown>;
}

export interface IJobHandler<TJobParams = unknown, TTaskParams = unknown> {
  processJob: (job: IJobResponse<TJobParams, TTaskParams>, task: ITaskResponse<TTaskParams>) => Promise<void>;
  sendCallBacks?: (jobId: string, taskId: string, status: OperationStatus) => Promise<void>;
}

export interface IPermittedJobTypes {
  ingestionNew: string;
  ingestionUpdate: string;
  ingestionSwapUpdate: string;
  exportJob: string;
}

export interface ITaskConfig {
  [key: string]: unknown;
  type: string;
  maxAttempts: number;
}

export interface ITasksConfig {
  [key: string]: ITaskConfig;
}

export type IngestionJobParams = z.infer<typeof ingestionJobParamsSchema>;
export type FindPolygonPartsResponse = FeatureCollection<Polygon, PolygonPartExtended>;

/**
 * Properties of a Layer Parts feature as written into the exported GeoPackage.
 * Snake_case column names per product requirement; missing optional values are `null` so the
 * column always exists (fixed schema). `fid` is generated by the GeoPackage itself and is not set here.
 */
export interface ExportFeatureProperties {
  id: string;
  description: string | null;
  sensors: string[];
  product_id: string;
  product_type: string;
  product_version: string;
  imaging_time_begin_utc: Date;
  imaging_time_end_utc: Date;
  ingestion_date_utc: Date;
  resolution_deg: number;
  resolution_meter: number;
  horizontal_accuracy_ce90: number;
  countries: string[] | null;
  source_name: string;
  cities: string[] | null;
}

export type ExportPolygonPartsResponse = FeatureCollection<Polygon, ExportFeatureProperties>;

//TODO: extend from base schema in raster-shared
export interface ValidationTaskParameters extends IngestionValidationTaskParams {
  processingState: ProcessingState | null;
  errorsSummary: ValidationAggregatedErrors;
}

export interface FeatureResolutions {
  resolutionMeter: number;
  resolutionDegree: number;
}
